"""Curated source catalog for transparent relationship-learning resources."""

from __future__ import annotations

from typing import TypedDict


class SourceCatalogItem(TypedDict):
    name: str
    url: str
    group: str
    summary: str
    structure: str
    quality_notes: str
    themes: tuple[str, ...]
    scenes: tuple[str, ...]


SOURCE_CATALOG: tuple[SourceCatalogItem, ...] = (
    {
        "name": "Kinsey Institute",
        "url": "https://kinseyinstitute.org/",
        "group": "国际研究机构",
        "summary": "人类性学、亲密关系与身心健康研究中心，适合作为成人亲密、边界和性健康议题的高可信背景源。",
        "structure": "研究项目、公开科普、档案资源、学术新闻、教育资源。",
        "quality_notes": "大学研究机构来源，适合做理论锚点；项目只保存派生摘要和跳转链接。",
        "themes": ("亲密研究", "成人关系", "性健康", "身心因素", "边界伦理"),
        "scenes": ("热恋", "承诺", "分歧", "修复"),
    },
    {
        "name": "Kinsey Confidential",
        "url": "https://kinseyconfidential.org/",
        "group": "国际研究机构",
        "summary": "面向公众的性教育与亲密问题科普入口，可辅助训练用户用清晰、非羞耻化语言谈亲密议题。",
        "structure": "问答、科普文章、教育材料、亲密关系主题。",
        "quality_notes": "适合成人教育和非诊断性学习，不作为医疗建议。",
        "themes": ("性教育科普", "亲密问题", "身体边界", "健康沟通"),
        "scenes": ("暧昧", "热恋", "承诺", "分歧"),
    },
    {
        "name": "Gottman Institute",
        "url": "https://www.gottman.com/blog/",
        "group": "伴侣关系研究",
        "summary": "伴侣关系、冲突修复、信任和长期连接的科普与训练文章，适合转化为关系修复卡片。",
        "structure": "博客、课程、方法论、研究介绍、专业培训。",
        "quality_notes": "关系教育领域高知名度来源；适合做修复、冲突和长期关系训练锚点。",
        "themes": ("冲突修复", "情绪承接", "长期关系", "信任维护"),
        "scenes": ("冲突", "修复", "承诺", "平淡"),
    },
    {
        "name": "Gottman Research",
        "url": "https://www.gottman.com/about/research/",
        "group": "伴侣关系研究",
        "summary": "介绍 Gottman 关系研究和互动观察脉络，适合训练用户识别关系模式和负向循环。",
        "structure": "研究历史、实验室脉络、模型说明、关系稳定性观察。",
        "quality_notes": "适合提供方法论背景，不保存原文。",
        "themes": ("关系观察", "互动模式", "稳定关系", "负面循环识别"),
        "scenes": ("热恋", "冲突", "平淡", "承诺"),
    },
    {
        "name": "CNVC Feelings Inventory",
        "url": "https://www.capitalnvc.org/feelings-inventory",
        "group": "沟通与情绪教育",
        "summary": "非暴力沟通中的感受词汇资源，适合训练用户把模糊情绪说清楚。",
        "structure": "感受词清单、情绪命名、沟通训练资源。",
        "quality_notes": "稳定公开引用页，内容标注来源于 CNVC；适合做情绪词典和情绪流动识别，不直接复制词表全文。",
        "themes": ("情绪词汇", "感受命名", "内在体验", "情绪流动"),
        "scenes": ("初识", "暧昧", "冲突", "修复"),
    },
    {
        "name": "CNVC Needs Inventory",
        "url": "https://www.capitalnvc.org/needs-inventory",
        "group": "沟通与情绪教育",
        "summary": "非暴力沟通中的需求词汇资源，适合把抱怨、冷淡和争吵还原为未满足需求。",
        "structure": "需求词清单、沟通资源、训练材料。",
        "quality_notes": "稳定公开引用页，内容标注来源于 CNVC；适合做需求雷达和请求表达训练。",
        "themes": ("需求识别", "非暴力沟通", "请求表达", "边界协商"),
        "scenes": ("冲突", "修复", "分歧", "承诺"),
    },
    {
        "name": "Greater Good Science Center",
        "url": "https://greatergood.berkeley.edu/topic/relationships",
        "group": "心理科普平台",
        "summary": "伯克利 Greater Good 关系主题，覆盖共情、善意、亲密连接和幸福感研究。",
        "structure": "主题文章、研究解读、练习建议、播客/视频内容。",
        "quality_notes": "适合作为积极关系和共情训练来源。",
        "themes": ("共情", "亲密关系", "善意沟通", "连接感"),
        "scenes": ("初识", "热恋", "平淡", "修复"),
    },
    {
        "name": "APA Relationships",
        "url": "https://www.apa.org/topics/marriage-relationships",
        "group": "心理科普平台",
        "summary": "美国心理学会婚姻与关系主题入口，适合做健康关系、压力和沟通的背景参考。",
        "structure": "主题文章、心理科普、实践建议、专业资源。",
        "quality_notes": "专业组织来源，适合做非诊断性关系教育。",
        "themes": ("健康关系", "沟通习惯", "压力管理", "关系维护"),
        "scenes": ("热恋", "冲突", "平淡", "承诺"),
    },
    {
        "name": "HelpGuide Effective Communication",
        "url": "https://www.helpguide.org/relationships/social-connection/effective-communication",
        "group": "实用沟通指南",
        "summary": "有效沟通、倾听、非语言信号和压力下沟通的实用指南。",
        "structure": "技能说明、常见障碍、练习建议、场景提示。",
        "quality_notes": "适合转化为训练任务和对话诊断清单。",
        "themes": ("有效沟通", "倾听", "非语言信号", "冲突降温"),
        "scenes": ("初识", "冲突", "修复", "分歧"),
    },
    {
        "name": "HelpGuide Conflict Resolution",
        "url": "https://www.helpguide.org/relationships/communication/conflict-resolution-skills",
        "group": "实用沟通指南",
        "summary": "冲突解决技能指南，适合训练降温、换位、共同问题定义和修复尝试。",
        "structure": "冲突机制、情绪调节、技能步骤、实践建议。",
        "quality_notes": "适合冲突和修复场景。",
        "themes": ("冲突解决", "情绪调节", "共同问题", "修复尝试"),
        "scenes": ("冲突", "修复", "分歧", "承诺"),
    },
    {
        "name": "Harvard Study of Adult Development",
        "url": "https://www.adultdevelopmentstudy.org/",
        "group": "长期发展研究",
        "summary": "长期成人发展研究，适合为长期幸福、关系质量和陪伴价值提供研究背景。",
        "structure": "研究介绍、出版物、团队、公开信息。",
        "quality_notes": "适合长期关系和生命阶段主题。",
        "themes": ("长期幸福", "关系质量", "陪伴", "人生发展"),
        "scenes": ("平淡", "承诺", "修复", "异地"),
    },
    {
        "name": "Love Matters China",
        "url": "https://lovematters.cn/",
        "group": "中文科普平台",
        "summary": "中文性教育与亲密关系科普平台，适合做中文语境下的亲密、边界和身体自主教育入口。",
        "structure": "性教育文章、问答、关系话题、健康科普。",
        "quality_notes": "中文友好来源；具体页面有效性需周期检查。",
        "themes": ("中文性教育", "亲密科普", "关系边界", "身体自主"),
        "scenes": ("初识", "暧昧", "热恋", "分歧"),
    },
    {
        "name": "CDC National Survey of Family Growth",
        "url": "https://www.cdc.gov/nchs/nsfg/",
        "group": "开放数据",
        "summary": "美国关于家庭成长、婚育史与性健康行为的权威调查数据入口。",
        "structure": "数据说明、问卷、公开数据文件、方法文档。",
        "quality_notes": "适合做宏观统计背景，不适合直接推断个体。",
        "themes": ("家庭成长数据", "婚育史", "性健康统计", "人口研究"),
        "scenes": ("承诺", "平淡", "分歧", "修复"),
    },
    {
        "name": "WHO Sexual Health",
        "url": "https://www.who.int/health-topics/sexual-health",
        "group": "公共卫生",
        "summary": "世界卫生组织性健康主题入口，用于健康、同意、权利和公共卫生背景。",
        "structure": "主题概览、指南、报告、新闻和政策资源。",
        "quality_notes": "权威公共卫生来源；项目仅用于学习摘要和链接跳转。",
        "themes": ("性健康", "生殖健康", "健康指南", "公共卫生"),
        "scenes": ("热恋", "承诺", "分歧", "修复"),
    },
    {
        "name": "Dibble Institute",
        "url": "https://dibbleinstitute.org/",
        "group": "关系教育项目",
        "summary": "循证关系教育课程机构，适合参考健康关系、青少年关系教育和沟通课程设计。",
        "structure": "课程项目、训练材料、研究证据、教育资源。",
        "quality_notes": "适合课程图谱和训练任务设计。",
        "themes": ("关系教育", "青少年课程", "健康关系", "沟通训练"),
        "scenes": ("初识", "暧昧", "冲突", "修复"),
    },
    {
        "name": "情感网",
        "url": "https://www.qg5.com/",
        "group": "中文情感社区",
        "summary": "中文情感故事与两性心理内容入口，可作为情绪流动、关系困惑和真实叙事的外部阅读渠道。",
        "structure": "情感故事、两性心理、情感应用、性情天地、音频内容等栏目。",
        "quality_notes": "社区内容需二次筛选；项目只登记链接和派生训练卡，不复制第三方全文。",
        "themes": ("情感故事", "两性心理", "情绪流动", "关系困惑"),
        "scenes": ("初识", "暧昧", "冲突", "修复"),
    },
    {
        "name": "恋小帮",
        "url": "https://www.lianxiaobang.cn/",
        "group": "中文互动工具",
        "summary": "恋爱场景话术和匿名情感讨论入口，可参考其场景分类思路补强错题改写与幽默互动。",
        "structure": "约会、表白、挽回、日常闲聊、匿名树洞等场景化内容。",
        "quality_notes": "话术类内容必须经过边界、同意和非操控过滤后才能转化为训练素材。",
        "themes": ("幽默回复", "错题改写", "暧昧张力", "情感树洞"),
        "scenes": ("初识", "暧昧", "复联", "修复"),
    },
    {
        "name": "中文幽默王",
        "url": "https://www.haha365.com/",
        "group": "中文幽默素材",
        "summary": "中文笑话和两性幽默入口，可用于学习轻松表达、低压破冰和日常调侃的结构。",
        "structure": "爱情笑话、夫妻笑话、校园笑话、顺口溜、两性杂谈等。",
        "quality_notes": "幽默内容需过滤羞辱、歧视和越界表达，只提炼结构和安全替代表达。",
        "themes": ("幽默互动", "爱情笑话", "低压破冰", "日常调侃"),
        "scenes": ("初识", "暧昧", "平淡", "热恋"),
    },
    {
        "name": "52笑话网",
        "url": "https://www.52xiaohua.com/",
        "group": "中文幽默素材",
        "summary": "生活笑话和夫妻日常段子入口，可辅助长期关系中的幽默互动和气氛修复。",
        "structure": "日常笑话、夫妻笑话、爱情笑话、生活糗事等。",
        "quality_notes": "只将适合成人学习、边界清晰、无羞辱的段子结构转为本地原创训练卡。",
        "themes": ("夫妻笑话", "长期连接", "幽默互动", "生活日常"),
        "scenes": ("平淡", "热恋", "修复", "承诺"),
    },
    {
        "name": "哄哄模拟器",
        "url": "https://hong.greatdk.com/",
        "group": "对话练习工具",
        "summary": "情景沟通模拟工具，适合参考其冲突场景设置来扩展错题改写和冲突修复训练。",
        "structure": "女友生气、约会迟到、家庭矛盾、日常误会等模拟场景。",
        "quality_notes": "适合作为交互机制参考；具体文本需本项目原创并通过非操控安全规则。",
        "themes": ("错题改写", "冲突修复", "情景模拟", "情绪承接"),
        "scenes": ("冲突", "修复", "分歧", "复联"),
    },
    {
        "name": "Paired",
        "url": "https://www.paired.com/",
        "group": "关系互动产品",
        "summary": "伴侣关系问答、游戏和测验产品，可作为长期连接、深度聊天和关系维护玩法参考。",
        "structure": "关系问题、情侣测验、互动游戏、课程内容和习惯提醒。",
        "quality_notes": "作为产品和互动结构参考，不复制题库；本地生成适配中文语境的原创练习。",
        "themes": ("长期连接", "深度聊天", "情侣游戏", "关系维护"),
        "scenes": ("热恋", "平淡", "承诺", "异地"),
    },
    {
        "name": "ChatRel",
        "url": "https://github.com/ruanflux/chatrel",
        "group": "开源关系分析",
        "summary": "本地聊天记录关系分析开源项目，提供多心理框架和关系时间线思路，可作为分析中心结构参考。",
        "structure": "聊天记录解析、关系框架、趋势轨迹、冲突事件时间线。",
        "quality_notes": "开源工程参考；接入前需核对许可证、隐私处理和本地化边界。",
        "themes": ("聊天分析", "长期趋势", "冲突修复", "关系图谱"),
        "scenes": ("平淡", "冲突", "修复", "承诺"),
    },
    {
        "name": "ChineseNlpCorpus",
        "url": "https://github.com/SophonPlus/ChineseNlpCorpus",
        "group": "开源语料导航",
        "summary": "中文 NLP 语料导航仓库，可用于寻找情感分析、对话理解和语义检索的公开数据入口。",
        "structure": "情感分析语料、问答语料、对话语料、文本分类资源索引。",
        "quality_notes": "仅作为数据源导航；实际使用需逐项核对许可证和数据合规性。",
        "themes": ("中文语料", "情感分析", "对话理解", "语义检索"),
        "scenes": ("初识", "冲突", "修复", "平淡"),
    },
)
